apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  APP_ENV: "prod"
  APP_DEBUG: "0"
  CORS_ALLOW_ORIGIN: "^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$"
  FRONTEND_URL: "http://192.168.139.2"
  DEFAULT_URI: "http://192.168.139.2"
