
services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

###> symfony/messenger ###
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
###< symfony/messenger ###

###< symfony/cache ###
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
###< symfony/cache ###

###< symfony/backend ###
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.docker
    ports:
      - "8080:80"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
###< symfony/backend ###

###< symfony/messeger-cosumer ###
  messenger:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.docker
    command: php bin/console messenger:consume async --time-limit=3600 -vv
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
###< symfony/messeger-cosumer ###

###< react/frontend ###
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
###< react/frontend ###

volumes:
  database_data:
  rabbitmq_data:
