
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

###> symfony/messenger ###
  rabbitmq:
     ports:
       - "5672:5672"
       - "15672:15672"
###< symfony/messenger ###

###< symfony/backend ###
  backend:
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./migrations:/app/migrations
      - ./public:/app/public
      - ./templates:/app/templates
      - ./bin:/app/bin
      - ./var:/app/var
###< symfony/backend ###

###< symfony/messeger-cosumer ###
  messenger:
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./var:/app/var
###< symfony/messeger-cosumer ###

###< react/frontend ###
  frontend:
    environment:
      CHOKIDAR_USEPOLLING: "1"
    volumes:
      - ./frontend:/app
      - /app/node_modules
###< react/frontend ###
