apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

images:
  - name: ghcr.io/OWNER/backend:latest
    newName: backend
    newTag: local
  - name: ghcr.io/OWNER/frontend:latest
    newName: frontend
    newTag: local

patches:
  - path: patches/image-pull-policy.yaml
