<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260414213243 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE todo_item ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE todo_item ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN todo_item.created_at IS \'\'');
        $this->addSql('ALTER INDEX idx_todo_item_todo_list_id RENAME TO IDX_40CA4301E8A7DCFA');
        $this->addSql('ALTER TABLE todo_list DROP CONSTRAINT fk_4a6048ec7e3c61f9');
        $this->addSql('ALTER TABLE todo_list ADD CONSTRAINT FK_1B199E077E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_4a6048ec7e3c61f9 RENAME TO IDX_1B199E077E3C61F9');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE todo_item ALTER id SET DEFAULT nextval(\'todo_item_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE todo_item ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN todo_item.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_40ca4301e8a7dcfa RENAME TO idx_todo_item_todo_list_id');
        $this->addSql('ALTER TABLE todo_list DROP CONSTRAINT FK_1B199E077E3C61F9');
        $this->addSql('ALTER TABLE todo_list ADD CONSTRAINT fk_4a6048ec7e3c61f9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_1b199e077e3c61f9 RENAME TO idx_4a6048ec7e3c61f9');
    }
}
