<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260426181018 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE api_key ADD description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE api_key ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE api_key ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX uniq_c912ed9d_key_value RENAME TO UNIQ_C912ED9DFF4925FB');
        $this->addSql('ALTER INDEX idx_api_key_user_id RENAME TO IDX_C912ED9DA76ED395');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE api_key DROP description');
        $this->addSql('ALTER TABLE api_key ALTER id SET DEFAULT nextval(\'api_key_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE api_key ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_c912ed9dff4925fb RENAME TO uniq_c912ed9d_key_value');
        $this->addSql('ALTER INDEX idx_c912ed9da76ed395 RENAME TO idx_api_key_user_id');
    }
}
