---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
        - name: backend
          imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messenger
spec:
  template:
    spec:
      containers:
        - name: messenger
          imagePullPolicy: Never
